name: 'Setup oneAPI'
description: 'Install oneAPI components'
branding:
  icon: 'download-cloud'
  color: 'blue'
inputs:
  components:
    description: 'Components to install'
    default: ''
  cache:
    description: 'Cache the install'
    default: true
  prune:
    description: 'Speed up save/restore by removing infrequently used files'
    default: true
  list:
    description: 'List the available components'
    default: false
outputs:
  root:
    description: 'Root directory of the installed components'
runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'
